# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ frontend ]
#   pull_request:
#     branches: [ frontend ]

jobs:
  build:

    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: ./13app/frontend/

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - run: pwd
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'
        cache-dependency-path: '13app/frontend/yarn.lock'
    - run: yarn install
    - run: yarn test
